name: Simple Python Test

on:
  push:
    branches: [ "feature/add-addition-functionality-new" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install pytest
      run: pip install pytest
      
    - name: List files for debugging
      run: |
        echo "=== 完整目录结构 ==="
        find . -name "*.py" | sort
        echo "=== tests 目录内容 ==="
        ls -la tests/ || echo "No tests directory"
        
    - name: Simple Python test
      run: |
        echo "=== 简单Python测试 ==="
        python -c "
import sys
print('Python version:', sys.version)
print('Python path:', sys.path)

# 测试导入
try:
    from app.app import add_numbers
    print('导入成功')
    result = add_numbers(5, 3)
    print('函数执行成功:', result)
except Exception as e:
    print('导入失败:', e)
    import traceback
    traceback.print_exc()
"
        
    - name: Run basic pytest
      run: |
        echo "=== 基础pytest ==="
        python -m pytest --version
        python -m pytest tests/ -v || echo "Pytest failed but continuing"
